## This is the main file for the first part of lab 2

0. Importing the necesarry modules and the data

In [1]:
from sklearn import datasets, svm, metrics
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection, tree, metrics

digits = datasets.load_digits()

1. Inspect the data. What is in there?

In [2]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

2. Split your data set into 70% training data (features and labels), and 30% test data

In [4]:
train_features, test_features, train_labels, test_labels = model_selection.train_test_split(digits.data, digits.target, test_size=0.30, random_state=42)

In [5]:
print("Number of training examples: ",len(train_features))
print("Number of test examples: ",len(test_features))
print("Number of total examples:", len(train_features)+len(test_features))

Number of training examples:  1257
Number of test examples:  540
Number of total examples: 1797


3. Set up a DecisionTreeClassifier as it comes in SciKitLearn. Use it with default parameters to train a decision tree classifier for the digits dataset based on the training data. Follow the tutorial (or the respective documentation) and produce a plot of the tree with graphviz. What can you learn from this about how the used algorithm handles the data?

In [7]:
clf1 = tree.DecisionTreeClassifier(random_state=0)
clf1.fit(train_features, train_labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [8]:

tree.export_graphviz(clf1, out_file="tree.dot")

import graphviz
with open("tree.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph).view()

'Source.gv.pdf'

4. Test the classifier with the remaining test data and analyse it using the metrics packages of SciKitLearn (classification report, confusion matrix). What do you see?

In [9]:
predicted1 = clf1.predict(test_features) 

print("Classification report for classifier %s:\n%s\n"
      % (clf1, metrics.classification_report(test_labels, predicted1)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(test_labels, predicted1))

Classification report for classifier DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best'):
              precision    recall  f1-score   support

           0       0.96      0.91      0.93        53
           1       0.80      0.70      0.74        50
           2       0.80      0.74      0.77        47
           3       0.83      0.89      0.86        54
           4       0.82      0.85      0.84        60
           5       0.90      0.91      0.90        66
           6       0.89      0.94      0.92        53
           7       0.92      0.84      0.88        55
           8       0.77      0.86      0.81        43
           9       

5. Change the parameters of the classifier, e.g., the minimum number of samples in a leaf / for a split, to see how the tree and the results are affected.

In [89]:
# Here I create the model object, DecisionTreeClassifier
clf2 = DecisionTreeClassifier(random_state=0, min_samples_split = 2, min_samples_leaf = 3) 
# min_sample_leaf : default 1, min_sample_split : default 2

# Here I train the model with the training data
clf2.fit(train_features, train_labels)

# This is to visualize the tree
tree.export_graphviz(clf2, out_file="tree.dot")
import graphviz
with open("tree.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph).view()


# Calculate the prediction using the test data
predicted2 = clf2.predict(test_features) 

# Printing the Classification report and the Confusion matrix
print("Classification report for classifier %s:\n%s\n"
      % (clf2, metrics.classification_report(test_labels, predicted2)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(test_labels, predicted2))

Classification report for classifier DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best'):
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        53
           1       0.84      0.84      0.84        50
           2       0.84      0.77      0.80        47
           3       0.78      0.87      0.82        54
           4       0.81      0.85      0.83        60
           5       0.93      0.85      0.89        66
           6       0.89      0.94      0.92        53
           7       0.82      0.84      0.83        55
           8       0.81      0.88      0.84        43
           9       

# Part 2

In [1]:
import ID3
import ToyData as td
import numpy as np
from sklearn import tree, metrics, datasets

In [2]:
attributes, classes, data, target, data2, target2 = td.ToyData().get_data()
id3 = ID3.ID3DecisionTreeClassifier()
myTree = id3.fit(data, target, attributes, classes)
print(myTree)
plot = id3.make_dot_data()
plot.render("testTree")


NODE CREATED
['Attributes: ', dict_keys(['color', 'size', 'shape'])]
[0 1 0]
['A: ', 'size']
['sub_attributes: ', {'color': ['y', 'g', 'b'], 'shape': ['r', 'i']}]
NODE CREATED
['Attributes: ', dict_keys(['color', 'shape'])]
[0 0 1]
['A: ', 'shape']
['sub_attributes: ', {'color': ['y', 'g', 'b']}]
NODE CREATED
['Attributes: ', dict_keys(['color'])]
[1 0 0]
['A: ', 'color']
['sub_attributes: ', {}]
NODE CREATED
NODE CREATED
----new iteration------
NODE CREATED
----new iteration------
NODE CREATED
['Attributes: ', dict_keys(['color', 'shape'])]
[0 0 1]
['A: ', 'shape']
['sub_attributes: ', {'color': ['y', 'g', 'b']}]
NODE CREATED
['Attributes: ', dict_keys(['color'])]
[1 0 0]
['A: ', 'color']
['sub_attributes: ', {}]
NODE CREATED
----new iteration------
NODE CREATED
['Attributes: ', dict_keys(['color'])]
[1 0 0]
['A: ', 'color']
['sub_attributes: ', {}]
NODE CREATED
NODE CREATED
----new iteration------
----new iteration------
----new iteration------
{'id': 0, 'label': None, 'attribute': '

'testTree.pdf'

In [ ]:
print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(target2, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(target2, predicted))